# Generated by Django 3.2.8 on 2021-12-17 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211217_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queries',
            options={'verbose_name': 'Query', 'verbose_name_plural': 'Queries'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='accepted_req_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.request'),
        ),
    ]
